### ISSUE TITLE
Security Exception on Initiate

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/zotero2bibl#13]
I get the following error message when trying to initiate the Zotero conversion in my local eXist using http://localhost:8080/exist/apps/zotero2bibl/get-zotero-data.xql?action=initiate&start=0&debug=true

```
exerr:ERROR sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target [at line 135, column 58]
In function:
	local:get-zotero-data(item()*) [149:19:/db/apps/zotero2bibl/get-zotero-data.xql]
	local:get-zotero() [208:47:/db/apps/zotero2bibl/get-zotero-data.xql]
```

**Comment by nathangibson** [comment]
It looks like it is working correctly on the server, so this is a low priority I suppose. Not sure if it has to do with my own configuration of Java or if something should be changed in the app.

**Comment by wsalesky** [comment]
@nathangibson What version of eXist are you running locally and is it different then what you are running on the server?

**Comment by nathangibson** [comment]
We are both running 3.5.0.

**Comment by wsalesky** [comment]
Okay, thanks. I'm looking into it.

**Comment by wsalesky** [comment]
@nathangibson Are you sure you don't get this error on the live site?

**Comment by wsalesky** [comment]
@nathangibson looks like this is a change in Zotero. Runs on the server because the server has SSL credentials. Still looking for a solution to be able to run it locally.

**Comment by wsalesky** [comment]
@nathangibson see: https://forums.zotero.org/discussion/67286/ssl-certificate-error-while-connecting-to-api-zotero-org

I have not yet been able to get this work, will take another look on Monday, let me know if you solve it before then.

**Comment by nathangibson** [comment]
Thanks, I'll take a look at this.

**Comment by nathangibson** [comment]
Looks like I am able to run this on my university machine. Perhaps the difference is the eXist version (4.4.0) or the fact that I am connected to the university network. Anyway, it provides a solution to the fact that I have a security exception on my home machine and eventually get a 504 when I make the request too many times in a row on the university server.

**Comment by wsalesky** [comment]
@nathangibson I'm using 4.4.0 and still cant run it locally, there is some sort of SSL certificate issue going on. I do not think it is eXist-db related though.  I'm happy to hear you can run it.

**Comment by nathangibson** [comment]
FYI, I tried a couple things that I hoped would let me bypass this from my home machine, but to no avail: 
1) Added the certs for eXist localhost and https://api.zotero.org to my JDK trust store.
2) Tried running it through the eXist SSL port.

**Comment by wsalesky** [comment]
@nathangibson Thanks for letting me know. I tried both of those as well. I haven't had much time to look more deeply into this, so let me know if you do end up finding a solution.

**Comment by nathangibson** [comment]
I also just tried changing the api reference to http://api.zotero.org (instead of https), but that didn't work either.

**Comment by wsalesky** [comment]
@nathangibson I think this is an eXist-db issue: 
https://sourceforge.net/p/exist/mailman/message/31996753/

I have not been able to get this to work.

**Comment by nathangibson** [comment]
OK, I'll take a look and see if it happens to work on my machine.

**Comment by nathangibson** [comment]
Whew, the solution you posted worked for me! Yippee!

I had to add **both** the certificate for the local exist and for Zotero's API to **both** the /Library/Java/JavaVirtualMachines and the /Library/Internet Plug-Ins/JavaAppletPlugin.plugin certificate stores. 

The command to extract the cert from the live service did not work for me. Instead I used certs I downloaded through Firefox for each of those hosts.

I will close this and you can reopen if you think further investigation is needed.

**Comment by nathangibson** [comment]
FYI: When I tried to run locally again today, it gave me the security exception again! I wondered what I had broken, until I discovered that Zotero had updated its security cert 3 days ago, so I had to reimport it into both of my keystores. Then it worked. Whew!
