### ISSUE TITLE
504 Gateway Time-out - nginx/1.10.3

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/zotero2bibl#14]
I'm consistently getting a 504 on this request: 
http://lmkwitg-xdb01.srv.mwn.de/exist/apps/zotero2bibl/get-zotero-data.xql?action=initiate&start=0&debug=true

It was working for a while yesterday. Perhaps a server decided my traffic was too heavy? 

I've restarted my computer and checked Zotero database integrity, but still nothing.

**Comment by wsalesky** [comment]
@nathangibson Does the script still run in the background? When I run it on the dev server the same thing happens, but the server continues to run the script. If not you may need to talk to your server person about the server settings.

**Comment by nathangibson** [comment]
Oh, hang on a bit. It looks like the entire eXist instance has gone down. :-( 
Maybe the problem that caused the crash also started the 504 errors yesterday and today. Let's see what happens when they get it back up.

**Comment by nathangibson** [comment]
@wsalesky I'm still running into this sometimes. Using the monex app, it looks as if (1) the query still runs in the background even after I get the 504 error (as you said), and (2) it starts adding additional processes! "Active DB processes" will increase from 1 to 2, even to 3 and "Running queries" will show get-zotero-data.xql multiple times, even if I've only made the request once. 

Is this an issue with the zotero2bibl code, or is it an eXist server setting that needs adjusting (such as allocating more memory)? Whichever it is, perhaps it is running out of memory and therefore triggering the unexpected shutdowns and db corruption?

Here's a screenshot of the memory usage:
![screenshot_2018-10-03 monitoring and profiling for exist monex 1](https://user-images.githubusercontent.com/3083452/46411055-1549c280-c71b-11e8-8d05-80f3c632d64b.png)

**Comment by wsalesky** [comment]
@nathangibson I think it is a memory issue. I will try to get this running locally today and see if I can debug.

**Comment by wsalesky** [comment]
@nathangibson I spent the morning trying to resolve the ssl certificate error with no luck. I will try to make some time tonight to look at the actual xquery to see what could be the problem.

**Comment by nathangibson** [comment]
Thanks, that is very kind!

**Comment by wsalesky** [comment]
@nathangibson are you using the paging option? You could try running a smaller number at a time, add a limit parameter:
exist/apps/zotero2bibl/get-zotero-data.xql?action=initiate&start=200&limit=50

Also, I suggest you comment out 
https://github.com/biblia-arabica/zotero2bibl/blob/master/get-zotero-data.xql#L115
to 
https://github.com/biblia-arabica/zotero2bibl/blob/master/get-zotero-data.xql#L124

I wonder if you are receiving a backoff or Retry-After response and firing a new request before the other has finished running and that is causing the multiple requests and memory usage.

**Comment by nathangibson** [comment]
Thanks. I tried both of those things and it strangely still launched a second query and I had to terminate both of them after getting the 504 to keep the memory from maxing out.
![screenshot_2018-10-04 monitoring and profiling for exist monex](https://user-images.githubusercontent.com/3083452/46460126-55f91880-c7bb-11e8-8351-e92a6b2632ae.png)

**Comment by nathangibson** [comment]
Unfortunately this is still happening even with limit=10.

**Comment by wsalesky** [comment]
@nathangibson are you running exactly what is in the github repository? Also, next time this happens can you click the 'Show stack' button? So far I have not been able to reproduce this, so some log information might be useful. Or should I try running it on your server? I don't want to bring anything down while you are working.

**Comment by wsalesky** [comment]
@nathangibson break through(ish)! I can run this locally now. (Running eXist-db in Docker) Hopefully I will be able to replicate your time out issue.

**Comment by nathangibson** [comment]
Yay!
I will try to update the server now with the github files to make sure that they are in sync. Then I will run it again and see. 
But earlier today I could do at least 10 without it acting crazy. 
Ya, it would be awkward if we bring down the server now. The disadvantage of running the dev app and production apps in the same exist instance is that some experiments affect both.

**Comment by nathangibson** [comment]
OK, here is the stack from the 2 processes it's running right now. 
The server is running this package: https://github.com/biblia-arabica/zotero2bibl/blob/dev/build/zotero2bibl-dev-1.5.xar. (Does it matter which version the other apps are, i.e. SROPHE and data?
I set the limit to 100 and it wasn't until the 4th request that it gave me the 504 and started going crazy.
![screenshot_2018-10-09 monitoring and profiling for exist monex](https://user-images.githubusercontent.com/3083452/46678172-5d1d8d80-cbe4-11e8-8cb5-e8b6c6ed23d6.png)
![screenshot_2018-10-09 monitoring and profiling for exist monex 1](https://user-images.githubusercontent.com/3083452/46678186-627ad800-cbe4-11e8-92c9-cc16d551116f.png)

**Comment by nathangibson** [comment]
Let me know if you need a login and I'll send you that privately.

**Comment by wsalesky** [comment]
@nathangibson I added a connection close header, this may help. See changes: 
https://github.com/biblia-arabica/zotero2bibl/tree/issue14

**Comment by nathangibson** [comment]
@wsalesky Thanks, I'll try it!

**Comment by wsalesky** [comment]
let me know how it goes.

**Comment by nathangibson** [comment]
OK, so far I can't get the get-zotero-data.xql processes to terminate, so I suppose I shouldn't try to update the file yet ...

**Comment by nathangibson** [comment]
Do you know how to kill the threads using the Java client? Or should I just update the file anyway? The stack doesn't seem to have updated since the screenshots I sent you.

**Comment by wsalesky** [comment]
@nathangibson I assume you tried using Monex and it did not work? 

You can try: 
http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/system&location=java:org.exist.xquery.functions.system.SystemModule

I think this is what Monex is using though, so it may not be effective.

**Comment by nathangibson** [comment]
Thanks. Good to know about but it didn't work :-(.
It doesn't seem to be running away with memory this time, so I think I will wait and see if these are still running tomorrow. If so, I can either go ahead with updating the file if you think it's safe enough, or I can ask our IT to restart eXist since it will be business hours. 
Thanks for your help with this.

**Comment by wsalesky** [comment]
It may be time to ask the list, it seems to be an issue with the http:request module, but since it works fine locally it also points to some server setup issue.

**Comment by nathangibson** [comment]
Unfortunately https://github.com/biblia-arabica/zotero2bibl/commit/af8bd6db0cae52cfa92112092355ca7791b781b3 doesn't seem to have worked either as the issue happened even on my local machine :-(
But maybe I'm just paging through too fast, since it seems like it works better if I wait a couple minutes between each request?
I'll see if the list has ideas once I get the processes terminated.

**Comment by wsalesky** [comment]
Okay, I saw your post on the list. I can chime in on the http:request issue once you get some advice on how to kill the running query.

**Comment by nathangibson** [comment]
Great!

**Comment by wsalesky** [comment]
@nathangibson I have been running the script on version 4.4.0, which may be why I have not been able to reproduce it.

**Comment by nathangibson** [comment]
After upgrading my local install, I have not been able to reproduce the problem. (And I think the request is actually faster, too.) Maybe that's all that was needed! I guess I should have tried that earlier (shrug)
Now for upgrading the university server ...

**Comment by wsalesky** [comment]
Well that is good news. Sorry that I didn't think to recommend you upgrade eXist!

**Comment by nathangibson** [comment]
Well, sorry for the extra work!
