### ISSUE TITLE
Add language of item from Zotero

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/zotero2bibl#16]
In https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm we need to add data from $rec?data?language

In the TEI this should go in /TEI/text/body/biblStruct/*[1]/textLang after the last idno. 

In Zotero, we are using comma-separated BCP-47 codes for language. The first code should go in `@mainLang` and the others as space-separated items in `@otherLangs`.

E.g., https://api.zotero.org/groups/538215/items/VB8RKV7K?format=json&include=data should have the following /TEI/text/body/biblStruct/monogr:

```
<monogr>
                    <editor>
                        <forename>Philip</forename>
                        <surname>Birnbaum</surname>
                    </editor>
                    <translator>
                        <forename>Philip</forename>
                        <surname>Birnbaum</surname>
                    </translator>
                    <title level="m">The Arabic Commentary of Yefet ben ‘Ali the Karaite on the Book of Hosea, Edited from Eight Manuscripts and Provided with a Critical Notes and an Introduction</title>
                    <idno type="URI">https://biblia-arabica.com/bibl/34RLRYC5</idno>
                    <idno type="URI">https://www.zotero.org/groups/biblia_arabica/items/34RLRYC5</idno>
                    <idno type="URI">https://www.zotero.org/groups/538215/items/34RLRYC5</idno>
                    <idno type="URI">http://www.worldcat.org/oclc/4571613</idno>
                    <textLang mainLang="ar" otherLangs="la gez"/>
                    <imprint>
                        <pubPlace>Philadelphia</pubPlace>
                        <publisher>The Dropsie College for Hebrew and Cognate Learning</publisher>
                        <date>1942</date>
                    </imprint>
                </monogr>
```

**Comment by wsalesky** [comment]
This has been added and tested. Data will need to be rerun.

**Comment by nathangibson** [comment]
@wsalesky Latest import from Zotero removed the textLang tag for some reason: https://github.com/biblia-arabica/biblia-arabica-data/commit/fa131709b6bda51da2d2298450018d6ef02e4635. 

Maybe has something to do with this commit https://github.com/biblia-arabica/zotero2bibl/commit/7c9c85bcf376c8e3873359584681f2ce03c8f039 or this one https://github.com/biblia-arabica/zotero2bibl/commit/6e97e5c5cbc253793883a1c75154943c3166bd3b#diff-6637c1ea59998cd7e14f992312dc3459L234

**Comment by wsalesky** [comment]
@nathangibson are you sure you are running the latest version of the zotero2bibl code? I ran it this morning and still get the language tag. (See below, record 257WGZQD.xml)
<img width="764" alt="screen shot 2019-03-06 at 2 36 53 pm" src="https://user-images.githubusercontent.com/1168206/53908445-56713600-401d-11e9-89ee-72daf1b9141c.png">

What version of eXist-db are you running this locally on?

**Comment by nathangibson** [comment]
You're right, I ran the new version and it's fine. Thanks.
