### ISSUE TITLE
Add JSON format 

### ISSUE THREAD

**Issue by wsalesky** [biblia-arabica/zotero2bibl#2]
Add JSON format parameter to gain access to notes and tags not output by  tei format. 
See: https://github.com/biblia-arabica/srophe-eXist-app/issues/6

The JSON serializer could probably use some version of this: 
https://github.com/biblia-arabica/arabic-bible-bibliography/blob/master/TEI%20custom2-include%20abstract.js

**Comment by wsalesky** [comment]
Still need to process the JSON into TEI, support now added to retrieve either JSON or TEI

**Comment by wsalesky** [comment]
@nathangibson I have a question about building the local ids. The current script uses the index number from the results returned, this does not match up to the ids your script generated.

I noticed there is an 'ID' tag in Zotero, do you want me to use that? The only problem is that there are sometimes multiples of these ids (see https://www.zotero.org/groups/538215/biblia_arabica/items/tag/ID%3A%2038).

Also, not all records have an ID, so I would need to generate a non repeating ID, or they will need to be added to Zotero.  

Other then that most of JSON to TEI is done, I will be checking it in shortly.

**Comment by nathangibson** [comment]
We are not using the URIs for anything yet, so it doesn't matter whether they match the existing ones. 

We initially thought of using the ID tag for the URIs, but I think this is unnecessary. What about using the Zotero item key to create the ID? E.g., https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/M4GAHIBT would be M4GAHIBT.

FYI, this doesn't need to be solved by tomorrow's demo, in case you were wondering. Everything should be fine as is for that. Thanks!

**Comment by wsalesky** [comment]
I think this library is ready to be used in production.
